import React from 'react'

const UsageDisclaimer = () => {
  return (
    <div className='usage-landingpage'>
        <div className='usage-container'>
            <h1>Usage Disclaimer</h1>

            <p>
            The Council’s content has been automatically generated by an AI and should be used for informational or leisure purposes only. 
            We cannot guarantee the accuracy, completeness, or timeliness of the information provided. Any actions taken based on this content are at your own risk. We recommend seeking qualified expertise or conducting further research to validate and supplement the information provided.
            </p>
        </div>
    </div>
  )
}

export default UsageDisclaimer
